
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Junta os dados em pequenos lotes antes de enviar, para não sobrecarregar a rede
  batch:

exporters:
  # 2A. O DESTINO DOS LOGS (Infraestrutura Legacy / Grafana)
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp/hyperdx:
    endpoint: "in-otel.hyperdx.io:4317" 
    tls:
      insecure: false
    headers:
      authorization: "aee98fd1-7a62-4297-bc73-85a22f40e337" 

service:
 
  pipelines:
    
    # Rota dos Traces: Entram pelo OTLP -> Vão para o HyperDX
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/hyperdx]
      
    # Rota das Métricas: Entram pelo OTLP -> Vão para o HyperDX
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/hyperdx]

    # Rota dos Logs: Entram pelo OTLP -> Vão para o Loki (Grafana)
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]