receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  # O NOVO EXPORTADOR MÁGICO PARA O HYPERDX
  otlphttp/hdx:
    endpoint: 'https://in-otel.hyperdx.io'
    headers:
      authorization: 'aee98fd1-7a62-4297-bc73-85a22f40e337' # <-- Substitui pela tua chave!
    compression: gzip
  
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/hdx, debug] 
    logs:
      receivers: [otlp]
      exporters: [otlphttp/hdx, debug] 
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/hdx, debug] 