// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: alarme.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlarmeRede struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdAlarme        string                 `protobuf:"bytes,1,opt,name=id_alarme,json=idAlarme,proto3" json:"id_alarme,omitempty"`
	EquipamentoIp   string                 `protobuf:"bytes,2,opt,name=equipamento_ip,json=equipamentoIp,proto3" json:"equipamento_ip,omitempty"`
	TipoEquipamento string                 `protobuf:"bytes,3,opt,name=tipo_equipamento,json=tipoEquipamento,proto3" json:"tipo_equipamento,omitempty"`
	NivelSeveridade int32                  `protobuf:"varint,4,opt,name=nivel_severidade,json=nivelSeveridade,proto3" json:"nivel_severidade,omitempty"`
	DescricaoFalha  string                 `protobuf:"bytes,5,opt,name=descricao_falha,json=descricaoFalha,proto3" json:"descricao_falha,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlarmeRede) Reset() {
	*x = AlarmeRede{}
	mi := &file_alarme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmeRede) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmeRede) ProtoMessage() {}

func (x *AlarmeRede) ProtoReflect() protoreflect.Message {
	mi := &file_alarme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmeRede.ProtoReflect.Descriptor instead.
func (*AlarmeRede) Descriptor() ([]byte, []int) {
	return file_alarme_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmeRede) GetIdAlarme() string {
	if x != nil {
		return x.IdAlarme
	}
	return ""
}

func (x *AlarmeRede) GetEquipamentoIp() string {
	if x != nil {
		return x.EquipamentoIp
	}
	return ""
}

func (x *AlarmeRede) GetTipoEquipamento() string {
	if x != nil {
		return x.TipoEquipamento
	}
	return ""
}

func (x *AlarmeRede) GetNivelSeveridade() int32 {
	if x != nil {
		return x.NivelSeveridade
	}
	return 0
}

func (x *AlarmeRede) GetDescricaoFalha() string {
	if x != nil {
		return x.DescricaoFalha
	}
	return ""
}

var File_alarme_proto protoreflect.FileDescriptor

const file_alarme_proto_rawDesc = "" +
	"\n" +
	"\falarme.proto\x12\x02pb\"\xcf\x01\n" +
	"\n" +
	"AlarmeRede\x12\x1b\n" +
	"\tid_alarme\x18\x01 \x01(\tR\bidAlarme\x12%\n" +
	"\x0eequipamento_ip\x18\x02 \x01(\tR\requipamentoIp\x12)\n" +
	"\x10tipo_equipamento\x18\x03 \x01(\tR\x0ftipoEquipamento\x12)\n" +
	"\x10nivel_severidade\x18\x04 \x01(\x05R\x0fnivelSeveridade\x12'\n" +
	"\x0fdescricao_falha\x18\x05 \x01(\tR\x0edescricaoFalhaB\aZ\x05./;pbb\x06proto3"

var (
	file_alarme_proto_rawDescOnce sync.Once
	file_alarme_proto_rawDescData []byte
)

func file_alarme_proto_rawDescGZIP() []byte {
	file_alarme_proto_rawDescOnce.Do(func() {
		file_alarme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alarme_proto_rawDesc), len(file_alarme_proto_rawDesc)))
	})
	return file_alarme_proto_rawDescData
}

var file_alarme_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alarme_proto_goTypes = []any{
	(*AlarmeRede)(nil), // 0: pb.AlarmeRede
}
var file_alarme_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alarme_proto_init() }
func file_alarme_proto_init() {
	if File_alarme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alarme_proto_rawDesc), len(file_alarme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alarme_proto_goTypes,
		DependencyIndexes: file_alarme_proto_depIdxs,
		MessageInfos:      file_alarme_proto_msgTypes,
	}.Build()
	File_alarme_proto = out.File
	file_alarme_proto_goTypes = nil
	file_alarme_proto_depIdxs = nil
}
