// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: tarefa.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Uma tarefa genérica para ser processada de forma assíncrona
type Tarefa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTarefa      string                 `protobuf:"bytes,1,opt,name=id_tarefa,json=idTarefa,proto3" json:"id_tarefa,omitempty"` // Identificador único (ex: "JOB-123")
	TipoAcao      string                 `protobuf:"bytes,2,opt,name=tipo_acao,json=tipoAcao,proto3" json:"tipo_acao,omitempty"` // O que é para fazer (ex: "GERAR_RELATORIO", "CALCULAR_DADOS")
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                   // A informação necessária (pode ser uma string genérica ou JSON)
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Momento em que foi criada
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tarefa) Reset() {
	*x = Tarefa{}
	mi := &file_tarefa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tarefa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tarefa) ProtoMessage() {}

func (x *Tarefa) ProtoReflect() protoreflect.Message {
	mi := &file_tarefa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tarefa.ProtoReflect.Descriptor instead.
func (*Tarefa) Descriptor() ([]byte, []int) {
	return file_tarefa_proto_rawDescGZIP(), []int{0}
}

func (x *Tarefa) GetIdTarefa() string {
	if x != nil {
		return x.IdTarefa
	}
	return ""
}

func (x *Tarefa) GetTipoAcao() string {
	if x != nil {
		return x.TipoAcao
	}
	return ""
}

func (x *Tarefa) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Tarefa) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_tarefa_proto protoreflect.FileDescriptor

const file_tarefa_proto_rawDesc = "" +
	"\n" +
	"\ftarefa.proto\x12\x02pb\"z\n" +
	"\x06Tarefa\x12\x1b\n" +
	"\tid_tarefa\x18\x01 \x01(\tR\bidTarefa\x12\x1b\n" +
	"\ttipo_acao\x18\x02 \x01(\tR\btipoAcao\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB\aZ\x05./;pbb\x06proto3"

var (
	file_tarefa_proto_rawDescOnce sync.Once
	file_tarefa_proto_rawDescData []byte
)

func file_tarefa_proto_rawDescGZIP() []byte {
	file_tarefa_proto_rawDescOnce.Do(func() {
		file_tarefa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tarefa_proto_rawDesc), len(file_tarefa_proto_rawDesc)))
	})
	return file_tarefa_proto_rawDescData
}

var file_tarefa_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tarefa_proto_goTypes = []any{
	(*Tarefa)(nil), // 0: pb.Tarefa
}
var file_tarefa_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tarefa_proto_init() }
func file_tarefa_proto_init() {
	if File_tarefa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tarefa_proto_rawDesc), len(file_tarefa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tarefa_proto_goTypes,
		DependencyIndexes: file_tarefa_proto_depIdxs,
		MessageInfos:      file_tarefa_proto_msgTypes,
	}.Build()
	File_tarefa_proto = out.File
	file_tarefa_proto_goTypes = nil
	file_tarefa_proto_depIdxs = nil
}
